name: Update streak stats

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 03:00
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Run any time this file is modified
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@v1
        with:
          github_token: ${{ secrets.STREAK_STATS_TOKEN }}
          options: user=${{ github.repository_owner }}&theme=default&width="600"&theme=transparent&hide_border=true&border_radius=4.5&locale=en&short_numbers=false&date_format=&mode=daily&exclude_days=&sections=total%2Ccurrent%2Clongest&card_width=495&card_height=195&type=svg&background-type=solid&properties=background
          path: profile/streak.svg

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
